name: Makefile CI

on:
  push:
    branches: [ "v2-wip" ]
  pull_request:
    branches: [ "v2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install qemu
      # runner for test / run cmds in Makefile!
      run: sudo apt install qemu-system

    - name: Build zero
      # just to ensure build / compile occurs successfully! (enough for most cases)
      run: make build

    - name: Run tests
      # warn! : this job is effectively useless (for testing most funcs) as it is non exhaustive and many functions dont have tests [TODO]
      run: make test
